export const groupSelectedConstants = {
  GROUPS_SELECTED_GET_FAILURE: "GROUPS_SELECTED_GET_FAILURE",
  GROUPS_SELECTED_GET_REQUEST: "GROUPS_SELECTED_GET_REQUEST",
  GROUPS_SELECTED_GET_SUCCESS: "GROUPS_SELECTED_GET_SUCCESS",

  GROUPS_SELECTED_GET_PHOTOS_FROM_FAILURE: "GROUPS_SELECTED_GET_PHOTOS_FROM_FAILURE",
  GROUPS_SELECTED_GET_PHOTOS_FROM_REQUEST: "GROUPS_SELECTED_GET_PHOTOS_FROM_REQUEST",
  GROUPS_SELECTED_GET_PHOTOS_FROM_SUCCESS: "GROUPS_SELECTED_GET_PHOTOS_FROM_SUCCESS",

  GROUPS_SELECTED_GET_PHOTOS_TO_FAILURE: "GROUPS_SELECTED_GET_PHOTOS_TO_FAILURE",
  GROUPS_SELECTED_GET_PHOTOS_TO_REQUEST: "GROUPS_SELECTED_GET_PHOTOS_TO_REQUEST",
  GROUPS_SELECTED_GET_PHOTOS_TO_SUCCESS: "GROUPS_SELECTED_GET_PHOTOS_TO_SUCCESS",

  GROUPS_SELECTED_POST_PHOTO_SUCCESS: "GROUPS_SELECTED_POST_PHOTO_SUCCESS",
};
