export const groupConstants = {
  GROUPS_GET_FAILURE: "GROUPS_GET_FAILURE",
  GROUPS_GET_REQUEST: "GROUPS_GET_REQUEST",
  GROUPS_GET_SUCCESS: "GROUPS_GET_SUCCESS",

  GROUPS_GET_SELECTED_FAILURE: "GROUPS_GET_SELECTED_FAILURE",
  GROUPS_GET_SELECTED_REQUEST: "GROUPS_GET_SELECTED_REQUEST",
  GROUPS_GET_SELECTED_SUCCESS: "GROUPS_GET_SELECTED_SUCCESS",

  GROUPS_CLEAR_SELECTED_SUCCESS: "GROUPS_CLEAR_SELECTED_SUCCESS",

  PHOTOS_GET_SELECTED_FROM_FAILURE: "PHOTOS_GET_SELECTED_FROM_FAILURE",
  PHOTOS_GET_SELECTED_FROM_REQUEST: "PHOTOS_GET_SELECTED_FROM_REQUEST",
  PHOTOS_GET_SELECTED_FROM_SUCCESS: "PHOTOS_GET_SELECTED_FROM_SUCCESS",

  PHOTOS_GET_SELECTED_TO_FAILURE: "PHOTOS_GET_SELECTED_TO_FAILURE",
  PHOTOS_GET_SELECTED_TO_REQUEST: "PHOTOS_GET_SELECTED_TO_REQUEST",
  PHOTOS_GET_SELECTED_TO_SUCCESS: "PHOTOS_GET_SELECTED_TO_SUCCESS",

  PHOTOS_UPLOAD_SUCCESS: "PHOTOS_UPLOAD_SUCCESS",

  GROUPS_ADD_SUCCESS: "GROUPS_ADD_SUCCESS",
  GROUPS_UPDATE_SUCCESS: "GROUPS_UPDATE_SUCCESS",
  GROUPS_DELETE_SUCCESS: "GROUPS_DELETE_SUCCESS"
};
