export const roleConstants = {
    ROLES_GET_FAILURE: 'ROLES_GET_FAILURE',
    ROLES_GET_REQUEST: 'ROLES_GET_REQUEST',
    ROLES_GET_SUCCESS: 'ROLES_GET_SUCCESS',

    ROLES_ADD_SUCCESS: 'ROLES_ADD_SUCCESS',
    ROLES_UPDATE_SUCCESS: 'ROLES_UPDATE_SUCCESS',
    ROLES_DELETE_SUCCESS: 'ROLES_DELETE_SUCCESS',
};